// Generated by scripts/sync-games.mjs. Do not edit.
import "../../../hook-hop/app/globals.css";

export default function GameEmbedLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return children;
}
