// Generated by scripts/sync-games.mjs. Do not edit.
import "../../../than-lan-san-muoi/app/globals.css";

export default function GameEmbedLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return children;
}
