import {
  access,
  cp,
  mkdir,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedRoot = path.join(root, "generated");
const embedRoot = path.join(root, "app", "embed");
const publicRoot = path.join(root, "public");
const iconRoot = path.join(publicRoot, "game-icons");
const assetRoot = path.join(publicRoot, "game-assets");

const exists = async (target) => {
  try {
    await access(target);
    return true;
  } catch {
    return false;
  }
};

const toPosix = (value) => value.split(path.sep).join("/");
const quote = (value) => JSON.stringify(value);

function assertSafeRelativePath(value, label, slug) {
  if (
    typeof value !== "string" ||
    value.length === 0 ||
    path.isAbsolute(value) ||
    value.split(/[\\/]/).includes("..")
  ) {
    throw new Error(`${slug}: ${label} must be a safe path inside its folder.`);
  }
}

function validateConfig(config, slug) {
  for (const key of ["name", "description", "category", "accent", "emoji"]) {
    if (typeof config[key] !== "string" || !config[key].trim()) {
      throw new Error(`${slug}: game.json is missing a non-empty "${key}".`);
    }
  }

  if (!config.entry || !["html", "react"].includes(config.entry.type)) {
    throw new Error(`${slug}: entry.type must be "html" or "react".`);
  }

  if (config.icon) assertSafeRelativePath(config.icon, "icon", slug);

  if (config.entry.type === "html") {
    assertSafeRelativePath(config.entry.path, "entry.path", slug);
  } else {
    assertSafeRelativePath(config.entry.component, "entry.component", slug);
    assertSafeRelativePath(config.entry.styles, "entry.styles", slug);
  }
}

async function findGames() {
  const entries = await readdir(root, { withFileTypes: true });
  const found = [];

  for (const entry of entries) {
    if (!entry.isDirectory() || entry.name.startsWith(".")) continue;
    const slug = entry.name;
    const configPath = path.join(root, slug, "game.json");
    if (!(await exists(configPath))) continue;

    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
      throw new Error(
        `${slug}: game folder names must use lowercase kebab-case.`,
      );
    }

    const config = JSON.parse(await readFile(configPath, "utf8"));
    validateConfig(config, slug);
    found.push({ slug, folder: path.join(root, slug), config });
  }

  return found.sort(
    (a, b) =>
      (a.config.order ?? Number.MAX_SAFE_INTEGER) -
        (b.config.order ?? Number.MAX_SAFE_INTEGER) ||
      a.config.name.localeCompare(b.config.name, "vi"),
  );
}

async function copyFolderIcon(game) {
  if (!game.config.icon) return null;
  const source = path.join(game.folder, game.config.icon);
  if (!(await exists(source))) {
    throw new Error(`${game.slug}: icon file not found: ${game.config.icon}`);
  }
  const extension = path.extname(source).toLowerCase() || ".png";
  const filename = `${game.slug}${extension}`;
  await cp(source, path.join(iconRoot, filename));
  return `/game-icons/${filename}`;
}

async function makeReactEmbed(game) {
  const route = path.join(embedRoot, game.slug);
  await mkdir(route, { recursive: true });

  const componentAbsolute = path.join(game.folder, game.config.entry.component);
  const stylesAbsolute = path.join(game.folder, game.config.entry.styles);
  if (!(await exists(componentAbsolute))) {
    throw new Error(
      `${game.slug}: React component not found: ${game.config.entry.component}`,
    );
  }
  if (!(await exists(stylesAbsolute))) {
    throw new Error(
      `${game.slug}: stylesheet not found: ${game.config.entry.styles}`,
    );
  }

  const componentImport = toPosix(
    path.relative(route, componentAbsolute).replace(/\.(tsx?|jsx?)$/, ""),
  );
  const stylesImport = toPosix(path.relative(route, stylesAbsolute));

  await writeFile(
    path.join(route, "page.tsx"),
    `// Generated by scripts/sync-games.mjs. Do not edit.\n` +
      `export { default } from ${quote(componentImport)};\n`,
    "utf8",
  );
  await writeFile(
    path.join(route, "layout.tsx"),
    `// Generated by scripts/sync-games.mjs. Do not edit.\n` +
      `import ${quote(stylesImport)};\n\n` +
      `export default function GameEmbedLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n` +
      `  return children;\n` +
      `}\n`,
    "utf8",
  );

  return `/embed/${game.slug}`;
}

async function makeHtmlEmbed(game) {
  const source = path.join(game.folder, game.config.entry.path);
  if (!(await exists(source))) {
    throw new Error(
      `${game.slug}: HTML entry not found: ${game.config.entry.path}`,
    );
  }

  const sourcePublic = path.join(game.folder, "public");
  const target = path.join(assetRoot, game.slug);
  if (await exists(sourcePublic)) {
    await cp(sourcePublic, target, { recursive: true });
  } else {
    await mkdir(target, { recursive: true });
    await cp(source, path.join(target, path.basename(source)));
  }

  const relativeFromPublic = path.relative(sourcePublic, source);
  if (relativeFromPublic.startsWith("..")) {
    await cp(source, path.join(target, path.basename(source)));
    return `/game-assets/${game.slug}/${path.basename(source)}`;
  }
  return `/game-assets/${game.slug}/${toPosix(relativeFromPublic)}`;
}

async function run() {
  const games = await findGames();

  await rm(embedRoot, { recursive: true, force: true });
  await rm(iconRoot, { recursive: true, force: true });
  await rm(assetRoot, { recursive: true, force: true });
  await mkdir(generatedRoot, { recursive: true });
  await mkdir(embedRoot, { recursive: true });
  await mkdir(iconRoot, { recursive: true });
  await mkdir(assetRoot, { recursive: true });

  const manifest = [];
  for (const game of games) {
    const iconUrl = await copyFolderIcon(game);
    const embedUrl =
      game.config.entry.type === "react"
        ? await makeReactEmbed(game)
        : await makeHtmlEmbed(game);

    manifest.push({
      slug: game.slug,
      name: game.config.name,
      description: game.config.description,
      category: game.config.category,
      accent: game.config.accent,
      emoji: game.config.emoji,
      iconUrl,
      embedUrl,
    });
  }

  const output =
    `// Generated by scripts/sync-games.mjs. Do not edit.\n\n` +
    `export type GameDefinition = {\n` +
    `  slug: string;\n` +
    `  name: string;\n` +
    `  description: string;\n` +
    `  category: string;\n` +
    `  accent: string;\n` +
    `  emoji: string;\n` +
    `  iconUrl: string | null;\n` +
    `  embedUrl: string;\n` +
    `};\n\n` +
    `export const games = ${JSON.stringify(manifest, null, 2)} as const satisfies readonly GameDefinition[];\n`;

  await writeFile(path.join(generatedRoot, "games.ts"), output, "utf8");
  console.log(`Synced ${games.length} game${games.length === 1 ? "" : "s"}.`);
}

run().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
